ALTER TABLE `subscription` ADD COLUMN `shift_len` INT NOT NULL DEFAULT 0;
ALTER TABLE `subscription` ADD COLUMN `shift_type` ENUM('HOURS', 'DAYS') NOT NULL DEFAULT 'HOURS';
ALTER TABLE `subscription` ADD COLUMN `enabled` TINYINT NOT NULL DEFAULT 1;
ALTER TABLE `subscription` ADD FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE;
